install:
	ln -sf $(PWD)/search-file.sh $(SCRIPT)/sf
	ln -sf $(PWD)/igr.sh $(SCRIPT)/igr
	ln -sf $(PWD)/cheat-sheet.sh $(SCRIPT)/cheat
	ln -sf $(PWD)/bashrc.sh $(SCRIPT)/rc
	ln -sf $(PWD)/reload.sh $(SCRIPT)/reload
	ln -sf $(PWD)/path.sh $(SCRIPT)/path
	ln -sf $(PWD)/doc.sh $(SCRIPT)/doc
	ln -sf $(PWD)/comment.sh $(SCRIPT)/cmt
	ln -sf $(PWD)/extract.sh $(SCRIPT)/ex
	ln -sf $(PWD)/cheat-vim.sh $(SCRIPT)/cv
	ln -sf $(PWD)/cheat-tmux.sh $(SCRIPT)/ct
	ln -sf $(PWD)/cheat-ledger.sh $(SCRIPT)/cl
	ln -sf $(PWD)/journal-day.sh $(SCRIPT)/jd
	ln -sf $(PWD)/journal-week.sh $(SCRIPT)/jw
	ln -sf $(PWD)/zettel-new.sh $(SCRIPT)/zn
	ln -sf $(PWD)/zettel-last.sh $(SCRIPT)/zl
	ln -sf $(PWD)/zettel-search.sh $(SCRIPT)/zs
	ln -sf $(PWD)/zettel-tags.sh $(SCRIPT)/zt
	ln -sf $(PWD)/filter-tag.sh $(SCRIPT)/ft
	ln -sf $(PWD)/sh-shebang.sh $(SCRIPT)/shebang
	ln -sf $(PWD)/sh-here.sh $(SCRIPT)/here
	ln -sf $(PWD)/script-new.sh $(SCRIPT)/sn
	ln -sf $(PWD)/bit-ops.sh $(SCRIPT)/bit-ops
	ln -sf $(PWD)/colors.sh $(SCRIPT)/colors
